- workalendar/europe.py
Currently the Finnish independence day is named "Labour Day", it should be named "Independence Day" instead.
> Rename Finnish independence day

- CHANGELOG
- workalendar/core.py
- workalendar/tests/test_core.py
To be able to compute working days backwards, from a "target date" to a "start date".
> Allow a negative "delta" in the add_working_days method

- CHANGELOG
- README.rst
- workalendar/europe.py
- workalendar/tests/test_europe.py
Hi novapost, 
I added the Luxembourg in this pull request.
Christian
> Adding Luxembourg

- workalendar/europe.py
- workalendar/tests/test_europe.py
There was a naming error making Pentecost be called Whit Sunday in Sweden (not that any Swedes would know the English word for it anyway).
> Fix name of Pentecost in Sweden

- CHANGELOG
- workalendar/core.py
- workalendar/tests/test_core.py
I think both methods should behave the same if a datetime object is given.
> added datetime to date conversion to is_holiday() like in is_working_day()

- .gitignore
- CHANGELOG
- CONTRIBUTING.rst
- tox.ini
this pure-python project could have its tests executed via py.test instead of nosetests
> switch to py.test

- CHANGELOG
- workalendar/europe/netherlands.py
- workalendar/tests/test_europe.py
> Bugfix: New Year's Eve is not a holiday in Netherlands

- CHANGELOG
- README.rst
- workalendar/europe/__init__.py
- workalendar/europe/switzerland.py
- workalendar/tests/test_europe.py
Switzerland public holidays are canton-specific:
https://en.wikipedia.org/wiki/Public_holidays_in_Switzerland
Canton of Vaud doesn't have Labor day or boxing day, but has its own
"Lundi du Jeûne Fédéral" in september.
> Switzerland: add rules for canton of Vaud

- CHANGELOG
- workalendar/europe/slovenia.py
- workalendar/tests/test_europe.py
1 Jan and 2 Jan ([since recently](https://en.wikipedia.org/wiki/Public_holidays_in_Slovenia)) are work-free days in Slovenia.
> 1 and 2 Jan are holidays in Slovenia

- CHANGELOG
- workalendar/core.py
- workalendar/tests/test_asia.py
If WEEKEND_DAYS is provided in the calendar class then use it to define the weekend, otherwise the calendar author needs to implement get_weekend_days as before.
> Refactor get_weekend_days to use WEEKEND_DAYS more intelligently

- CHANGELOG
- workalendar/america/__init__.py
- workalendar/america/brazil.py
- workalendar/core.py
- workalendar/tests/test_america.py
- workalendar/tests/test_brazil.py
> Adding Brazil states and cities, fixing major flaws in workalendar

- CHANGELOG
- workalendar/europe/hungary.py
- workalendar/tests/test_europe.py
> Added Good Friday in the list of Hungarian holidays, as of the year 2017

- CHANGELOG
- setup.py
refs #74
Assigned a minimal setuptools version, to avoid naughty ``DistributionNotFound`` exceptions with obsolete versions.
I've been as permissive as possible, starting with a several-year-old minimum, that will guarantee that it should not disturb the requirement computation. If the user other requirements require a more recent version, they won't be locked out.
> Assigned a minimal setuptools version

- CHANGELOG
- workalendar/europe/slovakia.py
- workalendar/tests/test_europe.py
closes #205
While I was at it, I've reconfigured some variable christian days that were included in the `ChristianMixin`, but were configured as "fixed days".
* All saints day
* Christmas eve
* St Stephen's day
> De-duplicated XMas day, which was configured twice

- CHANGELOG
- workalendar/america/brazil.py
- workalendar/tests/test_brazil.py
> Fix city holidays in Brazil calendars

- .travis.yml
- CHANGELOG
- tox.ini
> Add Python 3.6 configuration in travis and tox.

- CHANGELOG
- workalendar/asia.py
- workalendar/canada.py
- workalendar/europe/hungary.py
- workalendar/europe/iceland.py
- workalendar/europe/ireland.py
- workalendar/europe/latvia.py
- workalendar/europe/netherlands.py
- workalendar/europe/portugal.py
- workalendar/europe/spain.py
- workalendar/oceania.py
- workalendar/usa.py
* Hungary: a more clever take on the Good Friday rule
* Iceland: using ``extend`` instead of ``+=``
* Ireland: a more clever take on Whit Monday rule
* Latvia: using ``extend`` for lists, instead of ``+=``
* Netherlands: using ``.append`` for just *one* day to add
* Spain: remove the ugly ``u''``
* Japan: readability changes
* Taiwan: using ``extend`` for lists, instead of ``+=``
* Canada: using ``extend`` and ``append`` for lists
* Australia: using ``extend`` instead of ``+=`` + minor code reflow
* USA: using ``extend`` and ``append`` when needed, fixed a few docstrings, removed unnecessary 'super' calls
> Minor cleanups

- CHANGELOG
- workalendar/tests/test_usa.py
- workalendar/usa/__init__.py
- workalendar/usa/alabama.py
- workalendar/usa/core.py
- workalendar/usa/louisiana.py
There are 3 Counties with specific holidays in Alabama:
* Baldwin County,
* Mobile County,
* Perry County
https://en.wikipedia.org/wiki/Public_holidays_in_the_United_States#Baldwin_County.2C_Alabama
Requires the #171 to be solved
> Alabama Counties

- README.rst
Sorry stupid error in the README - I put Hong Kong in Europe by mistake as it was the top list.
> Hong Kong is in Asia, not Europe

- CHANGELOG
- README.rst
- workalendar/america/__init__.py
- workalendar/america/brazil.py
- workalendar/tests/test_brazil.py
Created a brazilian calendar to consider working days for bank transactions. Given a day, this calendar allow to find the next working day by ignoring the weekends, fixed and non fixed holidays and the last working day of the year in Brazil (used only for internal bank transactions). If the given day is a working day, it will be returned.
> Brazil bank calendar

- .travis.yml
- setup.py
- tox.ini
Python 3.3 is buggy and not supported anymore, also Travis-CI removed the interpreter which makes tests to fail.
> Remove support for Python 3.3

- CHANGELOG
- workalendar/oceania.py
- workalendar/tests/test_oceania.py
- [ X] Tests with a significant number of years to be tested for your calendar.
- [ X] Changelog amended with a mention describing your changes.
This is a fix for the following:
- ANZAC day shifting for each state in Australia
- Adding Reconciliation Day for ACT
- Updating Family and Community Day for ACT
This closes #249 and #251.
> Australia Holidays

- CHANGELOG
- workalendar/africa/south_africa.py
- workalendar/tests/test_africa.py
> De-duplicate South Africa holidays

- CHANGELOG
- workalendar/core.py
- workalendar/tests/test_core.py
> Add the `get_working_days_delta` method to the core calendar class.

- CHANGELOG
- workalendar/america/colombia.py
- workalendar/core.py
- workalendar/tests/test_core.py
> Fixed usage examples of ``get_first_weekday_after()`` docstring + in code (calendars and tests)

- Changelog.md
- README.rst
- workalendar/africa/__init__.py
- workalendar/africa/angola.py
- workalendar/core.py
- workalendar/europe/portugal.py
- workalendar/tests/test_africa.py
- workalendar/tests/test_europe.py
refs #276 
- Adds Angola holidays
For information, read and make sure you're okay with the [CONTRIBUTING document](https://github.com/novafloss/workalendar/blob/master/CONTRIBUTING.rst#adding-new-calendars).
- Restores Portugal holidays that were of by 2013 to 2015. [wikipedia pt](https://pt.wikipedia.org/wiki/Feriados_em_Portugal#Feriados_eliminados_em_2013%E2%80%932015) [wikipedia en](https://en.wikipedia.org/wiki/Public_holidays_in_Portugal#Revoked_holidays_in_2013%E2%80%932015)
- Fixes Portugal holidays as carnival in not a national holiday (in some regions and some companies, and public workers sometimes get a break);
- Adds All Souls' Day to common [wikipedia](https://en.wikipedia.org/wiki/All_Souls%27_Day)
This closes #276 , closes #275 , closes #274 .
> Add Angola, fix Portugal holidays, All Souls' Day

- Changelog.md
- workalendar/africa/south_africa.py
- workalendar/exceptions.py
- workalendar/tests/test_africa.py
Cleans up SouthAfrica class and tests to take into account the specs of holidays that vary over the periods.
As a side-effect, it effectively cleans the duplicates that were generated by the previous code.
refs #285
> South Africa cleanup and extended class

- Changelog.md
- docs/basic.md
- tox.ini
- workalendar/core.py
- workalendar/exceptions.py
- workalendar/tests/test_core.py
* only standard library `date` and `datetime` types (or subtypes) are supported,
* added a new dedicated exception,
* added a paragraph in the documentation about this type support.
refs #294
> Securing the core function arguments to valid types

- Changelog.md
- workalendar/asia/singapore.py
- workalendar/tests/test_asia.py
> Singapore: update DEEPAVALI days up to 2020

- .travis.yml
- Changelog.md
- setup.py
- tox.ini
- Travis job configuration was upgraded to Xenial (16.04)
- ``tox.ini``: conditional requirement. We'll be using the last version of ``pandas`` compatible with Python 3.4, and the latest for other Python versions
refs #306 #304
> Bugfix: Resolve incompatibilities between latest Pandas and Python 3.4

- Changelog.md
- README.rst
- workalendar/asia/__init__.py
- workalendar/asia/china.py
- workalendar/tests/test_asia.py
- workalendar/tests/test_registry_asia.py
closes #304 
* replacing #304 to have a cleaner history,
* rearranged the docstring to fit the "label" value,
* added a test in the ISO registry tests
----
> Add new calendar: China

- Changelog.md
- README.rst
- setup.py
- workalendar/asia/__init__.py
- workalendar/asia/israel.py
- workalendar/tests/test_asia.py
refs #278
Taking over the excellent work by @armona and @tsehori, I've revamped their PR and make it a bit more light, by only keeping editions made to the Changelog, the Readme, and only the patches in the runtime code that were about ``Israel`` calendar class and tests.
will superseed and thus, closes #281 + close #278.
> Add israel calendar

- Changelog.md
- setup.py
- Solved the incompatibility between `pandas` latest version and Python
3.4. Upgraded travis distro to Xenial/16.04 LTS (#307).
- Added instructions about the usage of the `iso_register` decorator in
the pull-request template (#309).
**New Calendars**
- Added New Zealand, by @johnguant (#306).
- Added Paraguay calendar, following the work of @reichert (#268).
- Added China calendar, by @iamsk (#304).
- Added Israel, by @armona, @tsehori (#281).
> Release v4.0.0

- Changelog.md
- README.rst
- workalendar/europe/__init__.py
- workalendar/europe/scotland/__init__.py
- workalendar/europe/scotland/mixins/__init__.py
- workalendar/europe/scotland/mixins/autumn_holiday.py
- workalendar/europe/scotland/mixins/fair_holiday.py
- workalendar/europe/scotland/mixins/spring_holiday.py
- workalendar/europe/scotland/mixins/victoria_day.py
- workalendar/tests/__init__.py
- workalendar/tests/test_scotland.py
> Scotland calendars

- Changelog.md
- README.rst
- workalendar/tests/test_usa.py
- workalendar/usa/__init__.py
- workalendar/usa/american_samoa.py
> Added American Samoa (US territory)

- Changelog.md
- README.rst
- workalendar/core.py
- workalendar/tests/test_usa.py
- workalendar/usa/__init__.py
- workalendar/usa/guam.py
> Added Guam (Us Territory)

- Changelog.md
- README.rst
- workalendar/tests/test_usa.py
- workalendar/usa/__init__.py
- workalendar/usa/massachusetts.py
> Added Suffolk County, Massachusetts calendar

- Changelog.md
- workalendar/tests/test_usa.py
- workalendar/usa/core.py
These shift mechanisms were previously tested via the regular US calendars, but I felt like we needed to have dedicated isolated tests.
closes #335
> Added isolated tests for shifting rules for US Calendars

- Changelog.md
- README.rst
- workalendar/america/__init__.py
- workalendar/america/barbados.py
- workalendar/tests/test_america.py
replaces and thus, closes #333
I've not found much of official sources, here are examples of two years on the official websites:
https://web.archive.org/web/20090806030650/http://www.barbados.gov.bb/bdospublichol2.htm
https://labour.gov.bb/wp-content/uploads/PDF/Public-Holidays-for-the-Year-2019.pdf
> Add Barbados calendar

- Changelog.md
- workalendar/asia/china.py
- workalendar/tests/test_asia.py
2019 Labour Day Holiday Shift for China, update at 20190322 by Chinese government.
refs #
http://www.gov.cn/zhengce/content/2018-12/06/content_5346276.htm
> 2019 Labour Day Holiday Shift for China, update at 20190322

- Changelog.md
- workalendar/oceania/australia.py
- workalendar/tests/test_oceania.py
Family & Community Day follows a "weird" non-mathematical rule
https://en.wikipedia.org/wiki/Family_Day
~~Will try to find a better way to handle this.~~
This PR explicits a bit better how this day is assigned, and adds a few tests to make sure that boundaries are correctly respected.
> Australia: Family & Community Day

- Changelog.md
- workalendar/tests/test_usa.py
- workalendar/usa/__init__.py
- workalendar/usa/california.py
Some Californian institutions or areas have different holidays:
* California education holidays
* California legal holidays
* Berkeley, California
* San Francisco, California
* West Hollywood, California
~~Source: https://en.wikipedia.org/wiki/Public_holidays_in_the_United_States#California~~
Updated source: https://en.wikipedia.org/wiki/Holidays_with_paid_time_off_in_the_United_States#California
Requires the issue #171 to be solved
> California specific holidays

- Changelog.md
- workalendar/africa/south_africa.py
- workalendar/tests/test_africa.py
This Pull Request supersedes and will close #350
Changes:
* fix erroneous test that was not pointing at the right year,
* moved the test into the canonical `SouthAfricaTest` class in `test_africa.py`
* changelog adjustements, to give @RichardOB all credits due :o)
> Richard ob south africa national elections 2019

- .travis.yml
- Changelog.md
- README.rst
- setup.py
- tox.ini
> Drop Python 3.4 support

- Changelog.md
- README.rst
- workalendar/tests/test_usa.py
- workalendar/usa/__init__.py
- workalendar/usa/alabama.py
- workalendar/usa/core.py
- workalendar/usa/florida.py
Some Florida subdivisions are using a different holiday calendar:
* Florida legal holidays
* Florida circuit courts
* Miami-Dade, Florida
~~source: https://en.wikipedia.org/wiki/Public_holidays_in_the_United_States#Florida~~
Updated sources:
* https://en.wikipedia.org/wiki/Holidays_with_paid_time_off_in_the_United_States#Florida
* http://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&Search_String=&URL=0600-0699/0683/Sections/0683.01.html (this one contradicts the other, MLK day happens on Jan 15th vs. Jan 18th)
Requires #171 to be solved first
> Florida specific holidays

- Changelog.md
- workalendar/asia/malaysia.py
- workalendar/tests/test_asia.py
> Malaysia Thaipusam dates for 2019 & 2020

- workalendar/asia/israel.py
- workalendar/tests/test_asia.py
Due to a previous PR fixing the Israeli Purim holiday behaviour during leap years, a new bug was introduced.
This fixes the fix and corrects Purim/Shushan Purim calculations :)
> Fixed Purim/Shushan Purim calculation once again

- Changelog.md
- workalendar/america/panama.py
- workalendar/tests/test_america.py
> Fix Panama calendar independence from Spain

- Changelog.md
- workalendar/tests/test_usa.py
- workalendar/usa/north_carolina.py
> Bugfix: Fixing North Carolina shift rules when Christmas Day happens on Saturday

- .travis.yml
- Changelog.md
- tox.ini
* Removed dedicated coverage tox jobs,
* Now coverage is executed for each tox job,
* Using the ``term:skip-covered`` option, only the classes with less than 100% coverage are displayed in the report, saving reading time
Bonus feature: with two less tox jobs, even with the coverage report generated for each Python version, execution time went from 2-3mn to 1mn30s on my local machine.
> A better coverage handling

- Changelog.md
- README.rst
- workalendar/core.py
- workalendar/europe/__init__.py
- workalendar/europe/turkey.py
- workalendar/tests/test_turkey.py
closes #371 ; superseeds and thus, closes #344
This branch is based on @tayyipgoren original work.
It adds an optional islamic delta to apply on-demand, by custom or specifically per year.
Also added tests for New Years shift, which happens on Sunday.
> Added Turkey calendar

- Changelog.md
- tox.ini
It should help tracking uncovered parts of workalendar.
```
---------- coverage: platform linux2, python 2.7.15-final-0 ----------
Name                                 Stmts   Miss  Cover   Missing
------------------------------------------------------------------
workalendar/africa/south_africa.py     105      1    99%   144
workalendar/america/brazil.py          205      1    99%   399
workalendar/america/canada.py          166      2    99%   102, 338
workalendar/asia/china.py               41      8    80%   66-67, 84-85, 91-92, 100-101
workalendar/asia/israel.py              51      2    96%   65, 79
workalendar/asia/malaysia.py            36      4    89%   77-78, 83-84
workalendar/asia/singapore.py           26      2    92%   71-72
workalendar/core.py                    442      3 …
```
> Display missing lines in coverage report

- Changelog.md
- workalendar/europe/luxembourg.py
- workalendar/tests/test_europe.py
Since this year there is a new national holiday in Luxembourg "Europe Day".
> add europe day for Luxembourg

- Changelog.md
- README.rst
- setup.py
- workalendar/asia/__init__.py
- workalendar/asia/japan.py
- workalendar/tests/test_asia.py
refs #369 
This PR attempts to create a new calendar, JapanBank that inherits from Japan. The [Bank of Japan
publicly lists their official holidays](https://www.boj.or.jp/en/about/outline/holi.htm/).
In addition, due to the change in emperor in 2019, there were some additional fixed holidays added that
year and some of the [variable holidays for 2020](https://www.timeanddate.com/holidays/japan/) were shifted around.
> Add JapanBank class

- Changelog.md
- workalendar/europe/united_kingdom.py
- workalendar/tests/test_europe.py
The Early May Bank Holiday has been moved to May 8th to commemorate the 75th anniversary of the end of WWII
closes #381
> Fixed United Kingom's 2020 holidays

- Changelog.md
- workalendar/europe/denmark.py
- workalendar/tests/test_europe.py
Fix #386
According to the following sources:
https://www.timeanddate.com/holidays/denmark/2019
https://publicholidays.dk/2019-dates/
Palm Sunday, Constitution Day, Christmas Eve and New Year's Eve are Observances and not non working days
This seems to be also true for past years (checked 2015, 2010, 2000)
> Fix Denmark, remove observances

- Changelog.md
- docs/iso-registry.md
- workalendar/registry.py
refs #375
**This PR introduces a breaking change**.
> Global registry now returns plain built-in dicts instead of OrderedDict's

- Changelog.md
- workalendar/asia/hong_kong.py
- workalendar/asia/japan.py
- workalendar/asia/taiwan.py
- workalendar/astronomy.py
- workalendar/core.py
- workalendar/tests/test_astronomy.py
- workalendar/tests/test_core.py
This Mixin was barely a mixin at all: none of its method was using ``self``.
it refers to #302, but not essentially. The goal of this refactoring is to simplify classes hierarchy, and it might also simplify the swap between `ephem` and `skyfield`.
> Removed ``EphemMixin`` in favor of astronomical functions

- Changelog.md
- setup.py
- workalendar/astronomy.py
> Drop (py)ephem dependency in favor of Skyfield

- setup.py
refs #406 / #408
This only adds the Python 3.8 classifier for the next release.
> Added Python 3.8 classifier in setup.py

- Changelog.md
- workalendar/exceptions.py
- workalendar/registry.py
- workalendar/tests/test_registry.py
refs #412
* Dropped unused lines in tests
* Trying to register a class that doesn't inherit from the core calendar class should raise an exception
> Improve registry tests

- Changelog.md
- README.rst
- docs/iso-registry.md
- workalendar/europe/__init__.py
- workalendar/europe/switzerland.py
- workalendar/tests/test_europe.py
- workalendar/tests/test_registry_europe.py
> Geneva Calendar

- Changelog.md
- setup.py
This releases fixes an important bug about the computation of the Thanksgiving Friday holiday in the USA.
- Commit for the tag:
- Back to dev commit:
- Github stuff
> v7.1.1 (Hotfix release)

- Changelog.md
- workalendar/europe/switzerland.py
* using the available API to get the first SUN of september, having a more readable code
* using a more "standard" way to return the holiday, with a tuple (date, label)
refs #420
> Refactored the computation of Genevan Fast holiday

- Changelog.md
- workalendar/asia/china.py
- workalendar/tests/test_asia.py
ModFile:
1. workalendar\asia\china.py
2. workalendar\tests\test_asia.py
3. Changelog.md
refs #
[China's public holidays  for 2020 EN](http://english.www.gov.cn/policies/infographics/201911/21/content_WS5dd677aac6d0bcf8c4c178dd.html)
[China's public holidays for 2020 CN](http://www.gov.cn/zhengce/content/2019-11/21/content_5454164.htm)
> Update China's public holidays for 2020

- Changelog.md
- workalendar/asia/malaysia.py
- workalendar/asia/singapore.py
- workalendar/tests/test_asia.py
refs #432 
Adds holidays in 2021 for:
- Singapore Deepavali (https://publicholidays.sg/deepavali/)
- Malaysia Deepavali (https://publicholidays.com.my/deepavali/)
- Malaysia Thaipusam (https://publicholidays.com.my/thaipusam/)
> Add Deepavali and Thaipusam in 2021 for Singapore and Malaysia

- Changelog.md
- docs/iso-registry.md
- workalendar/registry.py
- workalendar/tests/test_registry.py
refs #403, #375
Here are the changes in the ``registry.items()`` method API.
- This method is aliased to ``get_calendars()``. In a near release, the ``items()`` method will change its purpose.
- The ``get_calendars()`` method accepts an empty/missing ``region_codes`` argument to retrieve the full registry. Please see the [ISO Registry documentation](https://peopledoc.github.io/workalendar/iso-registry.html) for extensive usage docs.
----
> Changes in the registry.items API

- Changelog.md
- workalendar/america/canada.py
- workalendar/tests/test_canada.py
closes #454
It fixes two things:
* Family Day was introduced in 2013, workalendar was assuming it was there before
* In 2019, Family Day was moved from the 2nd to the 3rd MON of February
> Fix Family Day computation for British Columbia (Canada)

- Changelog.md
- workalendar/tests/test_usa.py
- workalendar/usa/core.py
- workalendar/usa/georgia.py
refs #451
* Fix Robert E. Lee's Birthday label rules (renamed as of year 2016 into the neutral "State Holiday")
* (hopefully) Fixed Washington's Birthday observance around Christmas time
* Fix Confederate Memorial Day label rules (renamed as of year 2016 into the neutral "State Holiday")
For the record:
Confederate Memorial Day, which was renamed into "State Holiday" used to happen on the 4th Monday of April each year, but for an unknown reason, in 2020, this state holiday happens on April 10th. And it looks like it's "just like that" and has no particular obvious reason to break the "4th Monday rule".
After thorough research  we've almost concluded that yes: it's "Governor's fiat" and I'll have to make a new research later this year
> Fix Georgia miscalculation of several state holidays

- Changelog.md
- workalendar/asia/china.py
- workalendar/tests/test_asia.py
This PR completes, and thus, closes #459.
> China support years as a dynamic warning

- Changelog.md
- workalendar/america/brazil.py
- workalendar/tests/test_brazil.py
It is really useful to allow reuse of this class. Brazilian bank calendar is not always the same.
For my use case, I just want to remove ash wednesday, but for that I have to override `get_variable_days()`.
Related #474
> Refactor BrazilBankCalendar to use `include_*` flags

- Changelog.md
- workalendar/america/argentina.py
- workalendar/tests/test_america.py
refs #476
* Fixed Argentina's "Malvinas Day" date for 2020, shifted to March 31st because of the coronavirus crisis.
* Fixed Argentina's label for "Malvinas Day" and "Día de la Memoria".
Checklist:
> Fix argentina holiday names shift 2020

- Changelog.md
- README.rst
- workalendar/africa/__init__.py
- workalendar/africa/kenya.py
- workalendar/tests/test_africa.py
> Add Kenyan calendar

- Changelog.md
- workalendar/europe/malta.py
There was no need to add it to the ``FIXED_HOLIDAYS`` property.
closes #469
> Fixed Malta calendar - January 1st was already included

- Changelog.md
- docs/iso-registry.md
- workalendar/registry.py
- workalendar/tests/test_registry.py
This is a **BREAKING CHANGE**.
You must use the ``get_calendars()`` to perform the same registry queries
refs #375, closes #491.
> The ``IsoRegistry.items()`` method has been removed from the API

- Changelog.md
- docs/iso-registry.md
- workalendar/registry.py
- workalendar/registry_tools.py
- workalendar/tests/test_registry.py
The ``get_calendar_class`` method will be dropped in a further release. In the meantime, they'll be both equivalent.
refs #375, closes #418.
> Alias ``IsoRegistry.get_calendar_class()`` to ``get()``

- Changelog.md
- docs/iso-registry.md
- workalendar/registry.py
- workalendar/tests/test_registry.py
> Removed the ``IsoRegistry.get_calendar_class()`` method

- Changelog.md
- workalendar/africa/angola.py
- workalendar/america/argentina.py
- workalendar/america/brazil.py
- workalendar/core.py
- workalendar/tests/test_africa.py
- workalendar/tests/test_america.py
- workalendar/tests/test_brazil.py
- workalendar/tests/test_usa.py
- workalendar/usa/alabama.py
- workalendar/usa/core.py
- workalendar/usa/florida.py
- workalendar/usa/louisiana.py
Also known as Mardi Gras, Carnaval, etc. it's used in at least 3 countries and some States / Counties in the USA.
> Moving Fat Tuesday calculation into the `workalendar.core` module

- Changelog.md
- workalendar/america/brazil.py
- workalendar/tests/test_brazil.py
taking over the branch initiated by @Edniemeyer
superseeds and thus, would close #516
> Brazil: Consciencia negra day is not a national holiday

- Changelog.md
- workalendar/europe/croatia.py
- workalendar/tests/test_europe.py
* Remembrance Day was added,
* Independence Day is no longer a holiday
* Statehood Day date has changed
closes #515
Sources used to consolidate this calendar:
* https://en.wikipedia.org/wiki/Public_holidays_in_Croatia
* https://www.officeholidays.com/countries/croatia/2020
* https://www.officeholidays.com/countries/croatia/2019
> Introducing the changes in Croatia holidays as of 2020

- Changelog.md
- workalendar/tests/test_africa.py
- workalendar/tests/test_brazil.py
- workalendar/tests/test_core.py
- workalendar/tests/test_europe.py
> Replace occurrences of `assertEquals` with `assertEqual` to clear warnings

- Changelog.md
- workalendar/america/argentina.py
- workalendar/america/brazil.py
- workalendar/america/paraguay.py
- workalendar/europe/portugal.py
- workalendar/tests/test_america.py
- workalendar/tests/test_brazil.py
- workalendar/tests/test_europe.py
> Use `include_immaculate_conception` flag for Portugal, Brazil, Argentina & Paraguay calendars

- Changelog.md
- README.rst
- workalendar/europe/__init__.py
- workalendar/europe/monaco.py
- workalendar/tests/test_europe.py
- workalendar/tests/test_registry_europe.py
> add monaco holidays

- Changelog.md
- workalendar/core.py
- workalendar/tests/__init__.py
> Fix PRODID pattern for iCal exports: using current workalendar version

- Changelog.md
- workalendar/tests/test_brazil.py
> Improve coverage of Brazil calendar

- Changelog.md
- workalendar/tests/test_canada.py
> Improve coverage of Canada (Nunavut) calendar

- Changelog.md
- workalendar/tests/test_asia.py
refs #546
We had to include the year 2021, because it offered the case that was missing in the `get_hebrew_independence_day` method.
> Improve coverage of Israel calendar

- Changelog.md
- workalendar/asia/singapore.py
- workalendar/tests/test_asia.py
Small refactor to trigger the KeyError a bit earlier.
refs #546
> Improve coverage of Singapore calendar

- .travis.yml
- Changelog.md
- README.rst
- contributing.md
- setup.py
- tox.ini
- workalendar/astronomy.py
> Deprecate Python 3.5

- Changelog.md
- README.rst
- setup.py
refs #330
On top of that, I've tried the following cases:
* run the 3.5 tests with the `python_requires` => Failed to install
* run the 3.5 tests without the `python_requires` => Failed to test, because of the `math.tau` change (only available in Python 3.6)
This will make users unable to install workalendar 12.x+ if they're still running Python 3.5 in their environment.
> Require Python version 3.6+ as of the next release.

- Changelog.md
- workalendar/tests/test_europe.py
Fixed the uncovered special case of Queen's Day when it falls on SUN.
refs #546
> Improve coverage for the Netherlands calendar

- Changelog.md
- workalendar/europe/romania.py
- workalendar/tests/test_europe.py
Liberation day coverage.
refs #564
> Improve coverage for the Romania calendar

- .travis.yml
- Changelog.md
- contributing.md
- setup.py
- tox.ini
- workalendar/america/barbados.py
- workalendar/america/canada.py
- workalendar/asia/china.py
- workalendar/core.py
- workalendar/registry.py
- workalendar/tests/__init__.py
- workalendar/tests/test_ical_export.py
- workalendar/tests/test_usa.py
- workalendar/usa/core.py
> Add a pyupgrade test job

- Changelog.md
- workalendar/europe/russia.py
- workalendar/tests/test_europe.py
The days between 2-5 have become a week off since 2005 (related to #578)
> Fix Russia New year holidays

- Changelog.md
- workalendar/europe/russia.py
- workalendar/tests/test_europe.py
> Fix COVID-19 2020 non-working days: these are not shifted

- Changelog.md
- workalendar/core.py
- workalendar/europe/belarus.py
- workalendar/europe/greece.py
- workalendar/europe/romania.py
- workalendar/europe/russia.py
- workalendar/europe/serbia.py
- workalendar/tests/test_europe.py
closes #530
* Set Orthodox Christmas as a parametrizable holiday.
* in Russia, December 25th is not a public holiday.
* Fixed several other Orthodox calendars
> Fixed Russia Christmas day & several other Orthodox calendars

- Changelog.md
- workalendar/asia/china.py
- workalendar/tests/test_asia.py
superseeds and thus, closes #595
Great job, @iamsk, although it's my fault if it required a rebase/squash and I think I screwed up the conflict resolution via Github interface... I really wanted to fix Russia's 2020 calendar before merging this new fix on China.
I'm ready to make a release right after that.
> Update China's public holidays for 2021.

- Changelog.md
- workalendar/asia/singapore.py
Add holidays from 2022 to 2030 for:
- Singapore (https://holidays.kayaposoft.com/public_holidays.php?year=2022&country=sgp&region=#)
> Add Deepavali from 2022 to 2030 for Singapore

- Changelog.md
- workalendar/astronomy.py
Numbers in time units divisions are generally integers (24/60/60), so they can be defined that way and Python3 will convert the division to a float automatically.
> Use integers for units division

- Changelog.md
- workalendar/asia/malaysia.py
- workalendar/tests/test_asia.py
Adds holidays up to 2024 for:
- Malaysia Deepavali (https://publicholidays.com.my/deepavali/)
- Malaysia Thaipusam (https://publicholidays.com.my/thaipusam/)
Checklist:
> Add Deepavali and Thaipusam until 2024 for Malaysia

- Changelog.md
- workalendar/core.py
- workalendar/europe/netherlands.py
- workalendar/tests/test_core.py
- workalendar/tests/test_europe.py
- Small fixes in Netherlands School calendars (#619).
- New method available in `core` module: `Calendar.get_iso_week_date()` to find the weekday X of the week number Y (#619).
- Improve Netherlands coverage (#546, #619).
> Netherlands school holidays refactor

- Changelog.md
- workalendar/usa/core.py
> Improve USA calendar coverage by removing the `get_washington_birthday_december` method

- Changelog.md
- tox.ini
refs https://github.com/domdfcoding/pyupgrade-directories/issues/13
> Temporary downgrade of `pyupgrade` to fix the `pyup_dirs`

- Changelog.md
- README.md
- setup.cfg
- workalendar/astronomy.py
superseeds, and thus, closes #614
> Replace pytz with zoneinfo (backports.zoneinfo for Python 3.6–3.8)

- Changelog.md
- README.md
- setup.cfg
**Major changes**
- API: New method available in `core` module: `Calendar.get_iso_week_date()` to find the weekday X of the week number Y (#619).
- Requirements: Replace pytz with `(backports.)zoneinfo`, thx to @eumiro (#614)
- Doc: Documented the different (in)compatibilities due to the use of `zoneinfo` (#614).
**Minor changes**
*Bugfix*
- Small fixes in Netherlands School calendars (#619).
- Temporary downgrade of `pyupgrade` to fix the `pyup_dirs`.
*Improving test coverage*
- Improve Netherlands coverage (#546, #619).
- Improve Russia coverage (#546).
- Improve USA calendar coverage by removing a method that wasn't used anyways (`get_washington_birthday_december()`). The method is implemented in both Indiana and Georgia State calendars, and is specific for each state, even if they …
> v15.0.0 Release

- Changelog.md
- workalendar/asia/taiwan.py
- workalendar/tests/test_asia.py
refs #628 (will be closed after the HF release)
Two extra-working days in 2021
* February, 20th
* September 11th,
**checklist**
> Hotfix: Taiwan exceptional working days in 2021

- Changelog.md
- workalendar/tests/test_usa.py
- workalendar/usa/core.py
> Bugfix: USA calendar would take the `shift_exceptions` into account

- Changelog.md
- tox.ini
> Requirements: Unpin `pyupgrade` library

- Changelog.md
- workalendar/europe/bulgaria.py
- workalendar/tests/test_europe.py
Bulgaria holidays are now computed using the Orthodox calendar, include shifting rules for holidays that fall on a week-end.
refs #596
> Multiple bugfixes for Bulgaria calendar

- Changelog.md
- workalendar/america/brazil.py
- workalendar/tests/test_brazil.py
Adding Easter Sunday, Corpus Christi and Good Friday.
This PR amends and would close #642 when it'll be merged.
> Update Cuiaba-Brazil holidays

- Changelog.md
- workalendar/america/barbados.py
- workalendar/tests/test_america.py
refs #
Two new non computable holiday have been added plus two fixes for boxing day that behaves differently in barbados and the collision of Emancipation Day and Independence Day.
Here is the official source for the fixes: https://labour.gov.bb/library/library-publications/holidays/
And the official source for the annoncement of the two public holiday: https://gisbarbados.gov.bb/download/official-gazette-january-2-2021-part-a-no-1-package/ (page4)
> Update Barbados calendar with public holiday 2021

- Changelog.md
- workalendar/asia/japan.py
- workalendar/tests/test_asia.py
refs #662 / superseeds and thus closes #663
> Japan calendar update because of the 2021 Olympics

- Changelog.md
- README.md
- workalendar/africa/__init__.py
- workalendar/africa/nigeria.py
- workalendar/tests/test_africa.py
> Add Nigeria calendar

- Changelog.md
- setup.cfg
- workalendar/core.py
- workalendar/tests/test_core.py
refs #536
This PR replaces `pyCalverter`, which is no more mantained and has an incompatible license (GPLv2), with [`convertdate`](https://pypi.org/project/convertdate/).
> Replace calverter with convertdate

- .gitignore
- Changelog.md
- README.md
- workalendar/asia/__init__.py
- workalendar/asia/philippines.py
- workalendar/core.py
- workalendar/tests/test_asia.py
refs #396
For information, read and make sure you're okay with the [Contributing guidelines](https://workalendar.github.io/workalendar/contributing.html#adding-new-calendars).
> Added philippines calendar

- Changelog.md
- README.md
- workalendar/europe/__init__.py
- workalendar/europe/guernsey.py
- workalendar/tests/test_europe.py
Add a new calendar for Guernsey. 
Here is the official website followed to implement the rule: https://gov.gg/holidaydates
One thing to note is that there are many similarities with the UK calendar but I've not tried to couple the two as there are some custom day shift in the UK that are not followed by Guernsey for what I can find. So it seems more trouble than it is worth. 
refs #
> Add Guernsey

- Changelog.md
- workalendar/asia/china.py
- workalendar/tests/test_asia.py
Update China's public holidays for 2022.
refs #
http://www.gov.cn/zhengce/content/2021-10/25/content_5644835.htm
> Update China's public holidays for 2022.

- Changelog.md
- docs/basic.md
> Doc: Fix the ``keep_datetime`` usage example in the "basic" doc

- Changelog.md
- workalendar/europe/united_kingdom.py
- workalendar/tests/test_europe.py
[State Funeral Announcement](https://www.gov.uk/government/news/bank-holiday-announced-for-her-majesty-queen-elizabeth-iis-state-funeral-on-monday-19-september)
> Update UK to include State Funeral Bank Holiday

- .github/workflows/ci.yml
- Changelog.md
- README.md
- docs/contributing.md
- setup.cfg
- tox.ini
* Upgraded usage of `tox` (now compatible with tox v4+)
* Added compatibility with Python 3.10 & 3.11
refs #706, #732
> Upgrade python and tox

- Changelog.md
- workalendar/asia/china.py
- workalendar/tests/test_asia.py
refs #
http://www.gov.cn/zhengce/content/2022-12/08/content_5730844.htm
closes #730
> Update China's public holidays for 2023.

- Changelog.md
- workalendar/europe/united_kingdom.py
- workalendar/tests/test_europe.py
[GOV.UK Press release](https://www.gov.uk/government/news/bank-holiday-proclaimed-in-honour-of-the-coronation-of-his-majesty-king-charles-iii)
> Add Coronation of His Majesty King Charles III Bank holiday in 2023 to the UK calendar.
