README.rst
workalendar/europe.py
workalendar/tests/test_europe.py

* added Slovak national holidays
* added Slovakia to README
* test for Slovakia
Signed-off-by: Adrian Matejov <a.matejov@centrum.sk>

europe: added Slovakia

---

workalendar/oceania.py
workalendar/tests/test_oceania.py
workalendar/usa.py

includes other fixes for Australia calendar + flake8 cleanups
should close #103

Australia boxing day

---

README.rst
workalendar/europe.py
workalendar/tests/test_europe.py

Just what the title says :)
This time with the correct branch name ;)

Add Portuguese holidays

---

CHANGELOG
README.rst
workalendar/europe.py
workalendar/tests/test_europe.py

Hi,
I have added the Netherlands as well after Luxembourg.
Christian

-Added Netherlands

---

README.rst
workalendar/europe.py
workalendar/tests/test_europe.py

New pull request to replace #104, as that one did not have correct holidays for Denmark and provided no unit tests.

Danish holidays

---

.travis.yml
CHANGELOG
tox.ini

testing against python 3.4 (and 3.5)

---

CHANGELOG
workalendar/asia.py
workalendar/tests/test_asia.py

Japan - 2016 - mountain day

---

README.rst
workalendar/europe.py
workalendar/tests/test_europe.py

Implemented Estonia's holiday calendar and tests for it.
Example data can be found here:
2015: http://www.vm.ee/en/estonian-holidays-2015
2016: http://www.officeholidays.com/countries/estonia/

Added Estonian calendar

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG

ref: https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

Add pull-request template with convenient checkboxes

---

CONTRIBUTING.rst

Europe has been reorganized, reflect changes in "Contributing" doc.

---

CHANGELOG
workalendar/europe/czech_republic.py
workalendar/tests/test_europe.py

Fix Good Friday computation in the Czech Republic

---

CHANGELOG
workalendar/europe/germany.py
workalendar/tests/test_europe.py

thx @zdenyv for the information.

Reformation Day as a National Holiday in Germany in the year 2017

---

CHANGELOG
README.rst
workalendar/europe/__init__.py
workalendar/europe/ireland.py
workalendar/tests/test_europe.py

For information, read and make sure you're okay with the [CONTRIBUTING document](https://github.com/novafloss/workalendar/blob/master/CONTRIBUTING.rst#adding-new-calendars).

Add Ireland

---

CHANGELOG
README.rst
workalendar/europe/__init__.py
workalendar/europe/austria.py
workalendar/tests/test_europe.py

Add Austria

---

CHANGELOG
README.rst
workalendar/europe/__init__.py
workalendar/europe/bulgaria.py
workalendar/tests/test_europe.py

thx @gregn610 for the great work!

Add Bulgaria - rebased from master

---

CHANGELOG
README.rst
workalendar/europe/__init__.py
workalendar/europe/austria.py
workalendar/europe/croatia.py
workalendar/tests/test_europe.py

Add Croatia

---

CHANGELOG
workalendar/europe/germany.py
workalendar/tests/test_europe.py

Fix 2016 Repentance Day in Saxony

---

CHANGELOG
workalendar/africa.py
workalendar/tests/test_africa.py

thx @gregn610 (replaces and fixes #173)

Fixed Historical and one-off holidays for South Africa

---

CHANGELOG
README.rst
workalendar/europe/__init__.py
workalendar/europe/latvia.py
workalendar/tests/test_europe.py

thx @gregn610.
this PR supersedes and closes #178.

Added Latvia calendar

---

CHANGELOG
README.rst
workalendar/asia.py
workalendar/core.py
workalendar/tests/test_asia.py

at the same time, it solves #194

Add Singapore calendar

---

CHANGELOG
workalendar/tests/test_usa.py
workalendar/usa.py

* less statements by using inheritance and splitting the Federal tests and the
State-based tests
* better comments for more clarity / readability
* configure Thanksgiving Friday by using a class variable instead of a Mixin

Refactoring the USA test modules

---

.travis.yml
CHANGELOG

Fix travis configuration for Python 3.5 and al.

---

workalendar/tests/test_usa.py
workalendar/usa/core.py

Fixing Federal Christmas Shift.

---

CHANGELOG
README.rst
workalendar/europe/__init__.py
workalendar/europe/russia.py
workalendar/tests/test_europe.py

refs #196 
For information, read and make sure you're okay with the [CONTRIBUTING document](https://github.com/novafloss/workalendar/blob/master/CONTRIBUTING.rst#adding-new-calendars).

[Feat] add russia calendar holidays (add-russia)

---

CHANGELOG
workalendar/core.py
workalendar/tests/test_core.py

Add working days using datetimes

---

Changelog.md

* Renamed CHANGELOG => Changelog.md,
* headings are atx-style (``#``, ``##``...),
* compacted headings using standard line feed number,
* adding the "v" prefix to have nicer URLS anchors

Changed Changelog format ; it's a Markdown file now

---

Changelog.md
README.rst
docs/_config.yml
docs/advanced.md
docs/basic.md
docs/index.md
workalendar/core.py

* Basic usage documentation, with methods you can use for a given country, to calculate holidays and working days,
* Advanced usage documentation, for integrators/developers, with helpers to build your own calendar depending on the formulas required by your holidays.
* These documentation pages should be visible on Github pages at the following URL: <https://peopledoc.github.io/workalendar/>

Added Basic and Advanced usage documentation

---

workalendar/africa/south_africa.py
workalendar/tests/test_africa.py

refs #285 
- [ x ] Adds a test for the national women's day test

Add test for women's day label

---

Changelog.md
workalendar/europe/slovenia.py
workalendar/tests/test_registry_europe.py

Fix ISO 3166-1 code for Slovenia

---

Changelog.md
README.rst
workalendar/oceania/__init__.py
workalendar/oceania/new_zealand.py
workalendar/tests/test_oceania.py
workalendar/tests/test_registry_oceania.py

refs #247 
For information, read and make sure you're okay with the [CONTRIBUTING document](https://github.com/novafloss/workalendar/blob/master/CONTRIBUTING.rst#adding-new-calendars).

Add New Zealand Calendar

---

.github/PULL_REQUEST_TEMPLATE.md
Changelog.md

Added instructions about the usage of `iso_register` in the PR template

---

Changelog.md
workalendar/europe/united_kingdom.py
workalendar/tests/test_europe.py

Fix 2012 and 2002 UK holiday.

---

Changelog.md
workalendar/europe/russia.py
workalendar/tests/test_europe.py

Fix Russia's Day of Unity date

---

Changelog.md
README.rst
workalendar/tests/test_usa.py
workalendar/usa/__init__.py
workalendar/usa/illinois.py

Added Chicago, Illinois calendar

---

Changelog.md
README.rst
workalendar/america/__init__.py
workalendar/europe/__init__.py
workalendar/europe/cayman_islands.py
workalendar/tests/test_europe.py

Add Cayman Islands.

---

Changelog.md
workalendar/europe/germany.py
workalendar/tests/test_germany.py

Add Berlin specific holidays. Fixes #340

---

.github/PULL_REQUEST_TEMPLATE.md
Changelog.md

Pull request template release

---

Changelog.md
README.rst

Sort Country list alphabetically & rearrange nested lists

---

.github/PULL_REQUEST_TEMPLATE.md
Changelog.md
contributing.md

Documentation: please do not change version in changelog/setup.py files.

---

.github/PULL_REQUEST_TEMPLATE.md
Changelog.md
Makefile

Improved packaging procedure

---

Changelog.md
workalendar/europe/romania.py
workalendar/tests/test_europe.py

Fix Romania, mixin order matters when mixing in OrthodoxMixin

---

Changelog.md
workalendar/europe/turkey.py
workalendar/tests/test_turkey.py

Update Turkey Republic Day.

---

Changelog.md
workalendar/tests/test_asia.py

Increase Malaysia coverage by adding tests for missing Deepavali & Thaipusam

---

Changelog.md
workalendar/asia/china.py
workalendar/tests/test_asia.py

* adding tests for missing fixed holidays exceptions,
* adding tests for the `is_working_day` override,
* adding tests for the `add_working_days` override,
* adding tests for the `sub_working_days` override,

Increase China coverage

---

.travis.yml
Changelog.md
README.rst
tox.ini

Added Python 3.8 compatibility

---

Changelog.md
workalendar/tests/test_usa.py
workalendar/usa/core.py

This pull-request superseeds and thus, closes #423. Also, it fixes #422

Fix USA: correct implementation for Thanksgiving Friday

---

Changelog.md
docs/advanced.md

Fix Advanced usage documentation about Thanksgiving Day

---

Changelog.md
README.rst
workalendar/europe/__init__.py
workalendar/europe/serbia.py
workalendar/tests/test_europe.py

refs #
For information, read and make sure you're okay with the [Contributing guidelines](https://github.com/novafloss/workalendar/blob/master/contributing.md#adding-new-calendars).

Added Serbia to the european countries

---

.travis.yml
Changelog.md

superseeds and thus, closes #447

Small changes to tox/travis config

---

Changelog.md
workalendar/asia/israel.py
workalendar/tests/test_asia.py

Fixing the Israel holidays

---

Changelog.md
README.rst
workalendar/europe/__init__.py
workalendar/europe/belarus.py
workalendar/tests/test_europe.py

refs #
For information, read and make sure you're okay with the [Contributing guidelines](https://github.com/novafloss/workalendar/blob/master/contributing.md#adding-new-calendars).

Adding holidays for Belarus

---

Changelog.md
workalendar/asia/__init__.py
workalendar/asia/hong_kong.py
workalendar/tests/test_asia.py

Hong Kong saturday is a working day

---

Changelog.md
workalendar/europe/lithuania.py

Fixed Lithuania calender to use the core flags for Assumption and All Saints

---

Changelog.md
workalendar/europe/netherlands.py

Small refactor in Netherlands calendar to use core constants

---

Changelog.md
workalendar/asia/israel.py
workalendar/tests/test_asia.py

Fix israel performance

---

Changelog.md
workalendar/asia/hong_kong.py
workalendar/tests/test_asia.py

Fixing duplicated holidays in Hong-Kong and Hong-Kong Bank holiday calendars

---

Changelog.md
workalendar/asia/hong_kong.py
workalendar/tests/test_asia.py

Hong kong holidays 2021

---

Changelog.md
workalendar/europe/cayman_islands.py

Small fixes (docstrings, use of extends, etc) on Cayman Islands calendar

---

Changelog.md
workalendar/europe/lithuania.py
workalendar/tests/test_europe.py

superseeds, and thus closes #512

Add All Souls Day to Lithuania

---

Changelog.md
workalendar/america/colombia.py
workalendar/tests/test_america.py

Small refactoring for the Colombia / added docstrings & comments to clarify exceptions
closes #509

Colombia refactor

---

Changelog.md
workalendar/tests/test_usa.py
workalendar/usa/california.py
workalendar/usa/core.py

Avoid Cesar Chavez Day duplicated shifts

---

Changelog.md
workalendar/europe/spain.py
workalendar/tests/test_registry_europe.py

refs #551 / superseeds and thus, closes #552 -- based on the cool contrib by @jbagot

Add ISO code decorator to Catalonia calendar

---

Changelog.md
README.rst
workalendar/europe/__init__.py
workalendar/europe/spain.py
workalendar/tests/test_europe.py
workalendar/tests/test_registry_europe.py
workalendar/tests/test_spain.py

Add all Spain regions

---

Changelog.md
workalendar/core.py
workalendar/tests/test_core.py

Improve coverage of the core.py module

---

Changelog.md
workalendar/oceania/new_zealand.py
workalendar/tests/test_oceania.py

Improve New Zealand test coverage

---

Changelog.md
README.rst
workalendar/core.py
workalendar/europe/__init__.py
workalendar/europe/netherlands.py
workalendar/tests/__init__.py
workalendar/tests/test_europe.py

Added School holidays for Netherlands

---

Changelog.md
README.rst
workalendar/europe/netherlands.py
workalendar/tests/test_europe.py

refs #
For information, read and make sure you're okay with the [Contributing guidelines](https://github.com/novafloss/workalendar/blob/master/contributing.md#adding-new-calendars).

Netherlands with carnival

---

Changelog.md
setup.cfg
setup.py

closes #576 
Couldn't resist, sorry :)

Switch from setup.py to setup.cfg

---

.travis.yml
Changelog.md

Let's live in the modern world!

Switched travis CI distro from bionic to focal

---

.github/workflows/ci.yml
Changelog.md
README.md
docs/contributing.md
setup.cfg
tox.ini

Added Python 3.9 support

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
Changelog.md

Setup py to cfg fixes

---

Changelog.md
workalendar/europe/russia.py
workalendar/tests/test_europe.py

Fix Russia calendar: non-working days shifted to MON when they happen on the week-end

---

Changelog.md
workalendar/core.py
workalendar/europe/russia.py
workalendar/tests/test_core.py
workalendar/tests/test_europe.py

Add Russia COVID-19 2020 non-working days

---

workalendar/europe/russia.py
workalendar/tests/test_europe.py

Adding the latest extra holidays of 2020 for Russia

---

Changelog.md
workalendar/europe/russia.py
workalendar/tests/test_europe.py

Fix Russia Holidays for the year 2021

---

Changelog.md
workalendar/core.py
workalendar/tests/__init__.py
workalendar/tests/test_ical_export.py

Use pathlib.Path instead of os.path.*

---

Changelog.md
docs/iso-registry.md
workalendar/africa/kenya.py
workalendar/africa/south_africa.py
workalendar/america/argentina.py
workalendar/america/barbados.py
workalendar/america/mexico.py
workalendar/asia/china.py
workalendar/asia/malaysia.py
workalendar/asia/singapore.py
workalendar/core.py
workalendar/europe/netherlands.py
workalendar/tests/__init__.py
workalendar/usa/core.py

This branch just adds a Changelog entry on top of #605.
closes #605

Use f-strings to format strings

---

Changelog.md
workalendar/africa/south_africa.py
workalendar/america/argentina.py
workalendar/america/canada.py
workalendar/america/paraguay.py
workalendar/asia/china.py
workalendar/core.py
workalendar/europe/germany.py
workalendar/europe/netherlands.py
workalendar/europe/scotland/__init__.py
workalendar/oceania/australia.py
workalendar/tests/test_asia.py
workalendar/tests/test_core.py
workalendar/tests/test_global_registry.py
workalendar/tests/test_registry.py
workalendar/tests/test_registry_africa.py
workalendar/tests/test_registry_america.py
workalendar/tests/test_registry_asia.py
workalendar/tests/test_registry_europe.py
workalendar/tests/test_registry_oceania.py
workalendar/tests/test_registry_usa.py
workalendar/tests/test_scotland.py
workalendar/usa/core.py
workalendar/usa/florida.py
workalendar/usa/georgia.py
workalendar/usa/indiana.py

This PR just amends the Changelog, compared to #606.
closes #606.

Simplify collections handling

---

.github/workflows/ci.yml
Changelog.md
README.md
workalendar/tests/__init__.py

While I was at it, I've added the MacOS tests.
refs #607

Added Windows to the test matrix & fix them

---

Changelog.md
workalendar/europe/russia.py
workalendar/tests/test_europe.py

Improve russia coverage

---

Changelog.md
workalendar/astronomy.py
workalendar/tests/test_astronomy.py

Improve coverage for the astronomy.py module

---

Changelog.md
workalendar/tests/__init__.py
workalendar/tests/test_core.py

Improve coverage for the `tests/__init__.py` module

---

Changelog.md
setup.cfg

released on 2021-02-26
**Changes**
- Hotfix: Taiwan exceptional working day on February, 20th 2021 (#628).
- Hotfix: September 11th is a working day in Taiwan (#628).
closes #628 
- Commit for the tag:
- Back to dev commit:
- Github stuff

Hotfix release: v15.0.1

---

Changelog.md
workalendar/core.py
workalendar/tests/test_core.py

Bugfix: `get_working_days_delta` method to integrate the `extra_holidays` and `extra_working_days` args

---

Changelog.md
workalendar/europe/spain.py
workalendar/tests/test_spain.py

This PR amends, solves conflict and thus, closes #643

Add St John the Baptist day for Catalonian calendar

---

Changelog.md
README.md

Workalendar has moved to its own organization

---

Changelog.md
workalendar/america/chile.py
workalendar/tests/test_america.py

replaces, and thus, closes #659

Chile calendar fixes

---

Changelog.md
setup.cfg
workalendar/__init__.py

Refs #657 (but not sure yet it closes it)

Remove setuptools from dependencies

---

Changelog.md
README.md

Only README file has been updated. Closes #673.
- Added badges: 
- Added installation instructions:

updated readme: added install instructions + badges

---

Changelog.md
README.md
workalendar/asia/__init__.py
workalendar/asia/kazakhstan.py
workalendar/europe/__init__.py
workalendar/europe/georgia.py
workalendar/europe/latvia.py
workalendar/tests/test_asia.py
workalendar/tests/test_europe.py

This "meta-PR" includes:
* [Remove duplicate Proclamation Day for Latvia (#686)](https://github.com/workalendar/workalendar/pull/686)
* [Add calendar for Kazakhstan (#688)](https://github.com/workalendar/workalendar/pull/688)
* [Add calendar for Georgia (country) (#687)](https://github.com/workalendar/workalendar/pull/687)

2022 january contributions

---

Changelog.md
workalendar/europe/switzerland.py
workalendar/tests/test_switzerland.py

Conditional 2-1/26-12 holidays in Neuchatel

---

.github/workflows/ci.yml
Changelog.md
README.md
docs/contributing.md
setup.cfg
tox.ini

* Removed CI & tests
* Amended documentation
closes #705

Removed compatibility with Python 3.6

---

Changelog.md
README.md
workalendar/africa/__init__.py
workalendar/africa/tunisia.py
workalendar/tests/test_africa.py

super great contribution by @macharmi. See #703 for the original PR.
superseeds and closes #703 (it was definitely my fault, the branch was made obsolete by my own inaction…)

Add Tunisia

---

Changelog.md
workalendar/europe/netherlands.py

The logic is more comprehensible using named functions and simple algebra instead of branchy/re-entrant logic and booleans.

Refactor NetherlandsWithSchoolHolidays.get_christmas_holidays
